"""Initial Commit

Revision ID: 977a743431f0
Revises: 
Create Date: 2023-06-01 22:14:46.708154

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '977a743431f0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
